# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic.u.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1127, 838)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.wallpaperButton = QtWidgets.QPushButton(self.centralwidget)
        self.wallpaperButton.setObjectName("wallpaperButton")
        self.gridLayout.addWidget(self.wallpaperButton, 5, 4, 1, 1)
        self.subredditComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.subredditComboBox.setEditable(True)
        self.subredditComboBox.setObjectName("subredditComboBox")
        self.subredditComboBox.addItem("")
        self.subredditComboBox.addItem("")
        self.gridLayout.addWidget(self.subredditComboBox, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 2, 1, 1)
        self.categoryComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.categoryComboBox.setObjectName("categoryComboBox")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.gridLayout.addWidget(self.categoryComboBox, 2, 4, 1, 1)
        self.darkModeCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.darkModeCheckBox.setText("")
        self.darkModeCheckBox.setObjectName("darkModeCheckBox")
        self.gridLayout.addWidget(self.darkModeCheckBox, 4, 4, 1, 1)
        self.subredditLabel = QtWidgets.QLabel(self.centralwidget)
        self.subredditLabel.setObjectName("subredditLabel")
        self.gridLayout.addWidget(self.subredditLabel, 1, 2, 1, 1)
        self.nextWallButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextWallButton.setObjectName("nextWallButton")
        self.gridLayout.addWidget(self.nextWallButton, 5, 2, 1, 1)
        self.limitComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.limitComboBox.setEditable(True)
        self.limitComboBox.setObjectName("limitComboBox")
        self.limitComboBox.addItem("")
        self.limitComboBox.addItem("")
        self.limitComboBox.addItem("")
        self.gridLayout.addWidget(self.limitComboBox, 3, 4, 1, 1)
        self.limitLabel = QtWidgets.QLabel(self.centralwidget)
        self.limitLabel.setObjectName("limitLabel")
        self.gridLayout.addWidget(self.limitLabel, 3, 2, 1, 1)
        self.categoryLabel = QtWidgets.QLabel(self.centralwidget)
        self.categoryLabel.setObjectName("categoryLabel")
        self.gridLayout.addWidget(self.categoryLabel, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(850, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setEnabled(True)
        self.photo.setScaledContents(False)
        self.photo.setAlignment(QtCore.Qt.AlignCenter)
        self.photo.setObjectName("photo")
        self.gridLayout.addWidget(self.photo, 0, 0, 1, 5)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 5, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1127, 26))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFiles.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KustomPyper"))
        self.wallpaperButton.setText(_translate("MainWindow", "Set as wallpaper"))
        self.subredditComboBox.setItemText(0, _translate("MainWindow", "wallpapers"))
        self.subredditComboBox.setItemText(1, _translate("MainWindow", "amoledbackgrounds"))
        self.label.setText(_translate("MainWindow", "Dark Mode :"))
        self.categoryComboBox.setItemText(0, _translate("MainWindow", "hot"))
        self.categoryComboBox.setItemText(1, _translate("MainWindow", "rising"))
        self.categoryComboBox.setItemText(2, _translate("MainWindow", "new"))
        self.categoryComboBox.setItemText(3, _translate("MainWindow", "top"))
        self.categoryComboBox.setItemText(4, _translate("MainWindow", "controversial"))
        self.subredditLabel.setText(_translate("MainWindow", "Subreddit : "))
        self.nextWallButton.setText(_translate("MainWindow", "Next wallpaper"))
        self.limitComboBox.setItemText(0, _translate("MainWindow", "10"))
        self.limitComboBox.setItemText(1, _translate("MainWindow", "25"))
        self.limitComboBox.setItemText(2, _translate("MainWindow", "50"))
        self.limitLabel.setText(_translate("MainWindow", "Limit :"))
        self.categoryLabel.setText(_translate("MainWindow", "Category :"))
        self.photo.setText(_translate("MainWindow", "Set a random wallpaper from reddit!"))
        self.saveButton.setText(_translate("MainWindow", "Save to Pictures"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
